@echo off
echo Matando proceso en puerto 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3000" ^| find "LISTENING"') do taskkill /F /PID %%a >nul 2>&1
echo Iniciando aplicacion...
npm start
